### ISSUE TITLE
Issue with Caliber 7.9: not fining the __init__.py

### ISSUE THREAD

**Issue by vnikoofard** [wheynelau/calibre-arxiv#2]
Hi,

I'm trying to install this plugin ([version 0.1.0](https://github.com/wheynelau/calibre-arxiv/releases/tag/v0.1.0)) by loading from a file. The downloaded zip file is ok and i can open it normally. There is a \__init\__.py file. But, the Calibre throws the following error.

calibre, version 7.9.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/vahid/Downloads/calibre.zip' is invalid. It does not contain a top-level __init__.py file

```
calibre 7.9  embedded-python: True
Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.38 Linux ('64bit', 'ELF')
('Linux', '6.8.0-76060800daily20240311-generic', '#202403110203~1714077665~22.04~4c8e9a0 SMP PREEMPT_DYNAMIC Thu A')
Python 3.11.5
Interface language: None
EXE path: /app/lib/calibre/bin/calibre
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 322, in add_plugin
  File "calibre/customize/ui.py", line 525, in add_plugin
  File "calibre/customize/ui.py", line 76, in load_plugin
  File "calibre/customize/zipplugin.py", line 297, in load
  File "calibre/customize/zipplugin.py", line 392, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/vahid/Downloads/calibre.zip' is invalid. It does not contain a top-level __init__.py file
```

I don't know the issue is with the Calibre or the zip file. Any help is appreciated.

**Comment by wheynelau** [comment]
@vnikoofard thanks, I will take a look
